# Generated by Django 2.2.4 on 2021-04-12 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20210410_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, through='tasks.Assignments', to='users.User'),
        ),
    ]
