# Generated by Django 2.2.4 on 2021-04-09 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('SU', 'solo user'), ('TA', 'team account')], default='SU', max_length=2),
        ),
    ]
