# Generated by Django 2.2.4 on 2021-04-18 00:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksession',
            name='duration',
            field=models.DurationField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
