# Generated by Django 2.2.4 on 2021-04-17 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksession',
            name='duration',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
