# Generated by Django 2.2.4 on 2021-04-18 21:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_worksession_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksession',
            name='duration',
            field=models.DurationField(default=datetime.time(17, 20, 56, 618682)),
        ),
    ]
