# Generated by Django 2.2.4 on 2021-04-19 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_auto_20210418_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksession',
            name='duration',
            field=models.DurationField(default=datetime.time(13, 51, 42, 590862)),
        ),
    ]
